spring:
  application:
    name: demo
server:
   port: 0
   servlet:
      context-path: /cinema
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

